# -*- coding: utf-8 -*-
from __future__ import annotations
from typing import List, Protocol
from langchain.schema import Document
from langchain.embeddings.base import Embeddings


class VectorStore(Protocol):
    """向量库抽象接口（可替换为 Milvus/Weaviate/PGVector 等）"""

    def build_from_documents(self, docs: List[Document], embeddings: Embeddings) -> None: ...
    def add_documents(self, docs: List[Document]) -> None: ...
    def similarity_search(self, query: str, k: int = 4) -> List[Document]: ...
    def save_local(self, path: str) -> None: ...
    def load_local(self, path: str, embeddings: Embeddings) -> None: ...
    def count(self) -> int: ...
