# -*- coding: utf-8 -*-
from __future__ import annotations
from typing import Dict, Any, Protocol, Sequence, List


class MetaStore(Protocol):
    """元数据存储抽象接口"""

    def set_meta(self, doc_id: str, meta: Dict[str, Any]) -> None: ...
    def get_meta(self, doc_id: str) -> Dict[str, Any]: ...
    def mget_meta(self, doc_ids: Sequence[str]) -> Dict[str, Dict[str, Any]]: ...
    def delete(self, doc_id: str) -> None: ...
    def all_ids(self) -> List[str]: ...
    def purge_namespace(self) -> None: ...
